# Generated by Django 4.2.11 on 2024-09-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_apply_applydate_alter_apply_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='applydate',
            field=models.DateField(null=True),
        ),
    ]
